### ISSUE TITLE
Full Update problem

### ISSUE THREAD

**Issue by Gwar17** [prasanthrangan/hyde-themes#1]
Hello,
The hyprland works great, but since I Installed libjxl: the system fails to fully update.When I try to delete it, It complains the programs need the dependency.
Maybe there is a solution other than uninstalling obs, mpv etc.

Wait for a reply at your earliest.

VT

**Comment by prasanthrangan** [comment]
Hey, i think `libjxl` is installed as a dependency. but it should not cause any issues with system update. So this is not related to this config.
