### ISSUE TITLE
Part of Ark not themed

### ISSUE THREAD

**Issue by ParaN3xus** [prasanthrangan/hyde-themes#23]
I am using Catppuccin Latte theme, but it seems part of Ark is not themed, like:
![image](https://github.com/user-attachments/assets/fd31fd26-c691-456b-b98f-d8856ad63093)

I checked kvantum manager preview and found backgrounds of some containers are pure black
![image](https://github.com/user-attachments/assets/95103117-c08e-4a97-a3aa-b08fdf360530)

I think this may be caused by some missing terms in kvantum config? But I don't really know what term is it.

**Comment by rishav12s** [comment]
![image](https://github.com/user-attachments/assets/9e6c67ef-a42e-468b-bde9-4c290f65b18e)
![image](https://github.com/user-attachments/assets/6176c993-c012-4038-8de8-a7b3773b9912)

works fine on my end

**Comment by ParaN3xus** [comment]
I've found a solution:

Check the PR mentioned below.
