### ISSUE TITLE
Nordic theme needs sudo for the compressed files 

### ISSUE THREAD

**Issue by kRHYME7** [prasanthrangan/hyde-themes#3]
Hello brother!👋 
You might remember, I talked about giving sudo for the compressed file a while back. 
The reason was, mostly Tcrypt's tar files gives these warnings/errors. Can we fix it to give permissions on the individual files inside the tar file, then compress it again ?  
![image](https://github.com/prasanthrangan/hyprdots-mod/assets/53417443/662a7462-c51d-4e9a-a6c5-b491f733f09b)

**Comment by prasanthrangan** [comment]
Hey, thats strange...  I'm not facing any errors with this...

![image](https://github.com/prasanthrangan/hyprdots-mod/assets/106020512/4e764512-a488-44eb-b6f6-8a109db44072)

**Comment by kRHYME7** [comment]
Okieee. Got those errors on an old directory. It's not giving those errors now.
